DB_NAME = "sacred" 
TABLE_ALUMNI_USERS = "alumni_users"
TABLE_OVERALL_ALUMNI = "overall_alumni"
TABLE_JOBS = "jobs"
TABLE_ACHIEVEMENTS = "achievements"

CREATE_ALUMNI_USERS_TABLE = f"""
CREATE TABLE IF NOT EXISTS `{TABLE_ALUMNI_USERS}` (
    id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL UNIQUE,
    password_hash VARCHAR(255) DEFAULT NULL,
    contact_number VARCHAR(20) DEFAULT NULL UNIQUE,
    academic_details JSON DEFAULT NULL,
    specialization VARCHAR(255) DEFAULT NULL,
    awards JSON DEFAULT NULL,
    honorary_degrees JSON DEFAULT NULL,
    books_authored JSON DEFAULT NULL,
    other_accolades JSON DEFAULT NULL,
    previous_experience JSON DEFAULT NULL,
    profile_image VARCHAR(255) DEFAULT NULL,

    role ENUM("admin", "alumni") DEFAULT "alumni",

    email_verified TINYINT(1) DEFAULT 0,
    email_otp VARCHAR(255) DEFAULT NULL,

    is_approved TINYINT(1) DEFAULT 0,
    rejection_reason VARCHAR(500) DEFAULT NULL,

    password_reset_token VARCHAR(255) DEFAULT NULL,
    token_expiry DATETIME DEFAULT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

CREATE_OVERALL_ALUMNI_TABLE = f"""
CREATE TABLE IF NOT EXISTS `{TABLE_OVERALL_ALUMNI}` (
    id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) DEFAULT NULL,
    mobile VARCHAR(20) DEFAULT NULL,
    
    degree ENUM("UG", "PG") DEFAULT "UG",
    specialization VARCHAR(255) DEFAULT NULL,
    batch YEAR DEFAULT NULL,
    roll_number VARCHAR(50) DEFAULT NULL,
    
    institution VARCHAR(255) DEFAULT NULL,
    department VARCHAR(255) DEFAULT NULL,
    
    status ENUM("active", "inactive", "verified") DEFAULT "active",
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

CREATE_JOBS_TABLE = f"""
CREATE TABLE IF NOT EXISTS `{TABLE_JOBS}` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    company VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    job_type VARCHAR(50) DEFAULT 'Full-time',
    salary VARCHAR(100) DEFAULT NULL,
    description TEXT,
    requirements TEXT,
    apply_link VARCHAR(500) DEFAULT NULL,
    is_blocked TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES `{TABLE_ALUMNI_USERS}`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

CREATE_ACHIEVEMENTS_TABLE = f"""
CREATE TABLE IF NOT EXISTS `{TABLE_ACHIEVEMENTS}` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    image_url LONGTEXT,
    is_blocked TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES `{TABLE_ALUMNI_USERS}`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

TABLE_GURUPADIGAM_MESSAGES = "gurupadigam_messages"

CREATE_GURUPADIGAM_MESSAGES_TABLE = f"""
CREATE TABLE IF NOT EXISTS `{TABLE_GURUPADIGAM_MESSAGES}` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    attachment_url JSON DEFAULT NULL,
    is_published TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES `{TABLE_ALUMNI_USERS}`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

TABLE_NEWSLETTERS = "newsletters"

CREATE_NEWSLETTERS_TABLE = f"""
CREATE TABLE IF NOT EXISTS `{TABLE_NEWSLETTERS}` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    attachment_url JSON DEFAULT NULL,
    thumbnail VARCHAR(500) DEFAULT NULL,
    is_published TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES `{TABLE_ALUMNI_USERS}`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

ALTER_NEWSLETTERS_ADD_THUMBNAIL = f"""
ALTER TABLE `{TABLE_NEWSLETTERS}` ADD COLUMN `thumbnail` VARCHAR(500) DEFAULT NULL AFTER `attachment_url`;
"""
